### PR TITLE
Added landscape option to esp_lcd_new_panel_ili9488()

### PR DESCRIPTION
**Pull request by jacobvc**

### CODE REVIEW

**Comment by atanisoft** [comment]
Thanks for the contribution!

**Comment by jacobvc** [comment]
Thanks,

FYI, I started this adventure when I decided to migrate some projects to
BSP based, using managed components as well as to support Square Line
Studio.

The current BSP is here https://github.com/jacobvc/esp-lcd-3-5-bsp. It is
functional, but still missing the SD Card operations. I hope to complete a
tidyup and  have a decent readme within a few days.

**Comment by atanisoft** [comment]
Looks like a great BSP library.

**Comment by jacobvc** [comment]
Since you have been so helpful, I have a few quick questions. FYI, I think
that my BSP is pretty usable but needs a bunch more in readme.md. I renamed
(moved) it to https://github.com/jacobvc/esp-lcd-3-5-diy

The little board I did has GPIO's for reset and touch IRQ but not for
backlight. I am not currently using the touch IRQ. Also, I can't connect to
board reset because I am only using the pin header that doesn't have reset.
In your experience, is reset needed? Is IRQ useful? I am thinking of
tweaking the board and am considering repurposing one of them to backlight.

Have you tested rotation? Does it work for you? If not, I would be willing
to invest some debug time.

**Comment by atanisoft** [comment]
the reset pin is useful but not 100% necessary, there is a software reset option which is used as backup when the reset pin is set to -1. The reset pin also can be connected to any GPIO and not necessarily to the EN pin.

Backlight is useful to expose but not critical as long as it is pulled high / low based on the TFT needs, I use LEDC to control the brightness in my usages.

Rotation has been lightly tested with LVGL but not extensively so there are likely some issues in there somewhere. If you do find any feel free to raise a PR.

**Comment by jacobvc** [comment]
Thanks ... you didn't answer the touch IRQ question.

**Comment by atanisoft** [comment]
Sorry missed that, touch IRQ isn't used by the esp_lcd_touch API at this time.

**Comment by jacobvc** [comment]
Thanks. That is what I thought, but I was too lazy to dig for it.

**Pull request merged**
